# Generated by Django 5.0.6 on 2024-05-22 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_name', models.CharField(max_length=50)),
                ('Min_Temperature', models.FloatField()),
                ('Max_Temperature', models.FloatField()),
                ('Min_Humidity', models.FloatField()),
                ('Max_Humidity', models.FloatField()),
                ('Min_Lightintensity', models.FloatField()),
                ('Max_Lightintensity', models.FloatField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('Lightintensity', models.FloatField()),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optibreed.room')),
            ],
        ),
    ]
