# Generated by Django 5.0.6 on 2024-07-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optibreed', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
