# Generated by Django 5.0.6 on 2024-07-31 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optibreed', '0004_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sensor_type', models.CharField(max_length=50)),
                ('Sensor_name', models.CharField(max_length=50)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optibreed.room')),
            ],
        ),
    ]
