# Generated by Django 5.0.6 on 2024-08-01 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optibreed', '0005_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='Lightintensity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Max_Lightintensity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='Min_Lightintensity',
        ),
        migrations.AddField(
            model_name='condition',
            name='Voltage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='room',
            name='Door_Open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='Door_Open_Timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='Max_Voltage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='room',
            name='Min_Voltage',
            field=models.FloatField(default=0.0),
        ),
    ]
