# Generated by Django 5.0.6 on 2024-08-02 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optibreed', '0006_remove_condition_lightintensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='Timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
