# Generated by Django 5.0.6 on 2024-08-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optibreed', '0007_alter_condition_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='DoorCondition',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Closed', max_length=10),
        ),
    ]
